import { StyleSheet, Platform } from "react-native";

export const ColorConstants = {
  primaryBrand: "#0047AB",
  primaryAccent: "#4A69E1",
  primaryLighter: "#8BA3FF",

  // Status & Feedback Colors
  success: "#2ECC71",
  warning: "#F39C12",
  danger: "#E74C3C",
  info: "#3498DB",

  // Neutral Palette
  background: "#F0F2F5",
  surface: "#FFFFFF",
  darkText: "#2C3E50",
  mediumText: "#556677",
  faintText: "#A0A7AD",

  // Base Colors
  inputBase: "#E3E8EE",
  headerBackground: "#fcfcfcff",
  shadow: "rgba(0, 0, 0, 0.15)",
  inputBorder: "#D8DCE3",

  // --- GLASSMOPRHISM COLORS (Retained for old definitions) ---
  glassBgTop: "#4c00ff",
  glassBgBottom: "#00ffc8",
  glassSurface: "rgba(255, 255, 255, 0.2)",
  glassBorder: "rgba(255, 255, 255, 0.8)",
  forgotPasswordText: "rgba(255, 255, 255, 0.9)",
  termsText: "rgba(255, 255, 255, 0.7)",
};

export const styles = StyleSheet.create({
  // --- General Layouts ---
  safeArea: { flex: 1, backgroundColor: ColorConstants.background },
  detailWrapper: { flex: 1, backgroundColor: ColorConstants.background },
  profileSafeArea: { flex: 1, backgroundColor: ColorConstants.background },

  // --- LOGIN SCREEN (PROFESSIONAL UI) ---
  loginScreenContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: ColorConstants.background,
  },
  keyboardAvoidingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
  },
  loginCardStyle: {
    backgroundColor: ColorConstants.surface,
    borderRadius: 20,
    padding: 40,
    width: "90%",
    maxWidth: 400,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.18,
    shadowRadius: 15,
    elevation: 12,
    alignItems: "center",
  },
  loginLogoContainer: {
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: ColorConstants.surface,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 40,
    borderWidth: 3,
    borderColor: ColorConstants.primaryAccent,
    overflow: "hidden",
  },
  loginLogoImage: {
    width: "80%",
    height: "80%",
    resizeMode: "contain",
  },
  loginWelcomeText: {
    fontSize: 30,
    fontWeight: "800",
    color: ColorConstants.darkText,
    marginBottom: 8,
    textAlign: "center",
  },
  loginSignInText: {
    fontSize: 17,
    color: ColorConstants.mediumText,
    marginBottom: 40,
    textAlign: "center",
  },
  loginInputGroup: {
    width: "100%",
    marginBottom: 25,
    position: "relative",
    paddingVertical: 12,
  },
  loginFloatingLabel: {
    position: "absolute",
    paddingHorizontal: 5,
    backgroundColor: ColorConstants.surface,
    borderRadius: 5,
    fontWeight: "600",
  },
  loginInputWrapper: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: ColorConstants.surface,
    borderWidth: 1.5,
    borderRadius: 10,
    height: 58,
    overflow: "hidden",
  },
  loginTextInput: {
    flex: 1,
    height: "100%",
    fontSize: 16,
    paddingHorizontal: 10,
    paddingVertical: 10,
    fontWeight: "500",
    color: ColorConstants.darkText,
  },
  loginPasswordToggle: {
    paddingHorizontal: 15,
    height: "100%",
    justifyContent: "center",
    alignItems: "center",
  },
  loginForgotPasswordButton: {
    marginTop: 5,
    marginBottom: 40,
    alignSelf: "flex-end",
    paddingHorizontal: 5,
  },
  loginForgotPasswordText: {
    fontSize: 15,
    fontWeight: "600",
    color: ColorConstants.mediumText,
  },
  loginButton: {
    backgroundColor: ColorConstants.primaryAccent,
    borderRadius: 10,
    height: 58,
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 40,
    shadowColor: ColorConstants.primaryAccent,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 8,
    elevation: 8,
  },
  loginButtonText: {
    color: ColorConstants.surface,
    fontSize: 18,
    fontWeight: "800",
    letterSpacing: 0.8,
  },
  loginTermsText: {
    fontSize: 13,
    color: ColorConstants.faintText,
    textAlign: "center",
    lineHeight: 18,
  },

  // --- TASK LIST & DETAIL STYLES ---
  header: {
    // PROFESSIONAL HEADER STYLE
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 15,
    backgroundColor: ColorConstants.surface,
    borderBottomWidth: 1,
    borderBottomColor: ColorConstants.inputBorder,
    shadowColor: ColorConstants.shadow,
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 5,
  },
  title: {
    // "TASKS" Title
    fontSize: 24,
    fontWeight: "800",
    color: ColorConstants.darkText,
    letterSpacing: 0.5,
  },
  profileIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: ColorConstants.inputBase,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: ColorConstants.darkText,
    overflow: "hidden",
  },
  profileIconImage: {
    width: "100%",
    height: "100%",
  },
  profileIconText: {
    color: ColorConstants.darkText,
    fontWeight: "bold",
    fontSize: 22,
  },
  // --- NAV BAR STYLES (PROFESSIONAL FIX) ---
  navbar: {
    flexDirection: "row",
  },
  taskCategoryContainer: {
    marginRight: 10,
  },
  navItem: {
    paddingVertical: 12,
    paddingHorizontal: 18,
    borderRadius: 25,
    backgroundColor: ColorConstants.surface,
    borderWidth: 1,
    borderColor: ColorConstants.inputBorder,
  },
  activeNavItem: {
    backgroundColor: ColorConstants.primaryAccent,
    borderColor: ColorConstants.primaryAccent,
    shadowColor: ColorConstants.primaryAccent,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
  navItemText: {
    fontSize: 14,
    fontWeight: "600",
    color: ColorConstants.mediumText,
  },
  activeNavItemText: {
    color: ColorConstants.surface,
    fontWeight: "700",
  },
  // --- SEARCH BAR STYLES ---
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: ColorConstants.surface,
    borderRadius: 15,
    marginVertical: 5,
    marginHorizontal: 15,
    paddingHorizontal: 15,
    shadowColor: ColorConstants.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
    borderWidth: 1,
    borderColor: ColorConstants.inputBorder,
  },
  searchIcon: {
    marginRight: 10,
    color: ColorConstants.darkText,
  },
  searchInput: {
    flex: 1,
    height: 48,
    fontSize: 16,
    color: ColorConstants.darkText,
  },
  content: {
    paddingHorizontal: 15,
    backgroundColor: ColorConstants.background,
  },
  card: {
    backgroundColor: ColorConstants.surface,
    borderRadius: 15,
    marginVertical: 8,
    padding: 20,
    borderLeftWidth: 5,
    shadowColor: ColorConstants.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  orderId: {
    fontSize: 18,
    fontWeight: "bold",
    color: ColorConstants.darkText,
  },
  statusTag: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 15,
    alignItems: "center",
  },
  statusText: {
    color: ColorConstants.surface,
    fontWeight: "bold",
    fontSize: 12,
  },
  cardBody: {
    flexDirection: "row",
    justifyContent: "space-between",
    flexWrap: "wrap",
  },
  cardDetails: {
    width: "48%",
  },
  detailText: {
    fontSize: 14,
    color: ColorConstants.darkText,
    marginBottom: 5,
  },
  label: {
    fontWeight: "bold",
    color: ColorConstants.darkText,
  },
  blueText: {
    color: ColorConstants.info,
    fontWeight: "bold",
  },
  noTasksText: {
    textAlign: "center",
    marginTop: 20,
    fontSize: 16,
    color: ColorConstants.faintText,
  },
  detailHeaderBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 15,
    paddingVertical: 15,
    backgroundColor: ColorConstants.surface,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    shadowColor: ColorConstants.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 4,
  },
  backButton: { padding: 5 },
  detailScreenTitle: {
    fontSize: 22,
    fontWeight: "700",
    color: ColorConstants.darkText,
  },
  detailPlaceholder: { width: 24 },
  detailScrollView: { padding: 15 },
  detailSection: {
    backgroundColor: ColorConstants.surface,
    borderRadius: 15,
    padding: 20,
    marginBottom: 15,
    shadowColor: ColorConstants.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  detailItemText: {
    fontSize: 15,
    color: ColorConstants.darkText,
    marginBottom: 8,
    lineHeight: 22,
  },
  detailLabel: {
    fontWeight: "bold",
    color: ColorConstants.darkText,
  },
  detailActiveStatus: {
    color: ColorConstants.success,
    fontWeight: "bold",
  },
  detailStatusText: {
    fontWeight: "bold",
    color: ColorConstants.surface,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
    overflow: "hidden",
  },
  uploadSection: {
    backgroundColor: ColorConstants.surface,
    borderRadius: 15,
    padding: 20,
    marginBottom: 15,
    shadowColor: ColorConstants.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  uploadTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: ColorConstants.darkText,
    marginBottom: 15,
  },
  uploadBox: {
    borderWidth: 2,
    borderColor: "#E6E6FA",
    borderStyle: "dashed",
    borderRadius: 15,
    padding: 25,
    alignItems: "center",
    marginBottom: 15,
    backgroundColor: "#F7F9FF",
  },
  uploadText: {
    fontSize: 16,
    fontWeight: "600",
    color: ColorConstants.faintText,
    marginTop: 10,
  },
  uploadSubText: {
    fontSize: 12,
    color: ColorConstants.faintText,
    marginTop: 5,
  },
  gallery: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 10,
  },
  thumbnailImage: {
    width: 80,
    height: 80,
    borderRadius: 10,
    marginRight: 10,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "#E6E6FA",
  },
  thumbnailAdd: {
    width: 80,
    height: 80,
    borderRadius: 10,
    backgroundColor: "#F7F9FF",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "#E6E6FA",
    borderStyle: "dashed",
  },
  commentsSection: {
    backgroundColor: ColorConstants.surface,
    borderRadius: 15,
    padding: 20,
    marginBottom: 15,
    shadowColor: ColorConstants.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  commentsTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: ColorConstants.darkText,
    marginBottom: 10,
  },
  commentsInput: {
    borderWidth: 1,
    borderColor: ColorConstants.inputBorder,
    borderRadius: 10,
    padding: 15,
    minHeight: 100,
    textAlignVertical: "top",
    fontSize: 16,
    backgroundColor: ColorConstants.inputBase,
    color: ColorConstants.darkText,
  },
  locationSection: {
    backgroundColor: ColorConstants.surface,
    borderRadius: 15,
    padding: 20,
    marginBottom: 15,
    shadowColor: ColorConstants.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  locationHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
  },
  locationTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: ColorConstants.darkText,
    marginLeft: 10,
  },
  locationText: {
    fontSize: 14,
    color: ColorConstants.darkText,
    marginLeft: 30,
    marginBottom: 5,
  },
  lastUpdatedText: {
    fontSize: 12,
    color: ColorConstants.faintText,
    marginLeft: 30,
    marginTop: 5,
  },
  actionButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
    padding: 15,
  },
  rejectButton: {
    flex: 1,
    backgroundColor: ColorConstants.danger,
    padding: 15,
    borderRadius: 15,
    marginRight: 10,
    alignItems: "center",
    shadowColor: ColorConstants.danger,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 8,
  },
  rejectButtonText: {
    color: ColorConstants.surface,
    fontWeight: "bold",
    fontSize: 16,
  },
  submitButton: {
    flex: 1,
    backgroundColor: ColorConstants.primaryAccent,
    padding: 15,
    borderRadius: 15,
    marginLeft: 10,
    alignItems: "center",
    shadowColor: ColorConstants.primaryAccent,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 8,
  },
  submitButtonText: {
    color: ColorConstants.surface,
    fontWeight: "bold",
    fontSize: 16,
  },
  // --- DISABLED BUTTON STYLES (Single Definition) ---
  disabledButton: {
    backgroundColor: ColorConstants.faintText,
    shadowColor: "transparent",
    elevation: 0,
  },
  disabledButtonText: {
    color: "#E0E0E0",
  },
  disabledInput: {
    backgroundColor: "#ECF0F1",
    color: ColorConstants.faintText,
  },
  // --- PROFILE STYLES ---
  profileHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#ECF0F1",
    backgroundColor: ColorConstants.surface,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    shadowColor: ColorConstants.shadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 8,
  },
  profileTitle: {
    fontSize: 24,
    fontWeight: "700",
    color: ColorConstants.darkText,
    letterSpacing: 1,
  },
  profileContent: {
    alignItems: "center",
    paddingTop: 30,
    backgroundColor: ColorConstants.background,
    flex: 1,
    width: "100%",
    maxWidth: 600,
    alignSelf: "center",
  },
  profileScrollView: {
    flexGrow: 1,
    backgroundColor: ColorConstants.background,
    paddingHorizontal: 20,
    alignItems: "center",
  },
  profileAvatarContainer: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: ColorConstants.surface,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 15,
    position: "relative",
    borderWidth: 3,
    borderColor: ColorConstants.primaryAccent,
    shadowColor: ColorConstants.shadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 8,
  },
  profileAvatar: { opacity: 0.8 },
  profileAvatarImage: {
    width: "100%",
    height: "100%",
    borderRadius: 60,
  },
  cameraIconContainer: {
    position: "absolute",
    bottom: 0,
    right: 0,
    backgroundColor: ColorConstants.primaryAccent,
    padding: 8,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: ColorConstants.background,
  },
  nameDisplayContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 5,
  },
  nameEditContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 5,
    backgroundColor: ColorConstants.surface,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderWidth: 1,
    borderColor: "#E6E6FA",
  },
  profileName: {
    fontSize: 24,
    fontWeight: "700",
    color: ColorConstants.darkText,
    marginRight: 10,
  },
  profileNameInput: {
    fontSize: 24,
    fontWeight: "700",
    color: ColorConstants.darkText,
    minWidth: 100,
  },
  nameEditIcon: {
    padding: 5,
  },
  profileEmail: {
    fontSize: 16,
    color: ColorConstants.mediumText,
    marginBottom: 30,
  },
  profileMenu: {
    width: "100%",
    marginBottom: 20,
    paddingHorizontal: 10,
  },
  profileMenuItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: ColorConstants.surface,
    paddingVertical: 15,
    paddingHorizontal: 15,
    borderRadius: 12,
    marginBottom: 10,
    shadowColor: ColorConstants.shadow,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 2,
  },
  profileMenuItemText: {
    flex: 1,
    marginLeft: 15,
    fontSize: 16,
    color: ColorConstants.darkText,
    fontWeight: "500",
  },
  logoutButton: {
    width: "95%",
    backgroundColor: ColorConstants.danger,
    padding: 15,
    borderRadius: 12,
    alignItems: "center",
    marginTop: 20,
    marginBottom: 30,
    shadowColor: ColorConstants.danger,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 8,
  },
  logoutButtonText: {
    color: ColorConstants.surface,
    fontSize: 18,
    fontWeight: "bold",
  },
  versionText: {
    fontSize: 14,
    color: ColorConstants.faintText,
    marginBottom: 20,
  },
  noNotificationsText: {
    fontSize: 18,
    color: ColorConstants.faintText,
    marginTop: 20,
    textAlign: "center",
  },
});
