import { StyleSheet, Platform } from 'react-native';

export const ColorConstants = {
    // Brand & Primary Palette
    primaryBrand: '#0047AB', 
    primaryAccent: '#4A69E1', // Vibrant Blue (Used for button, focus border)
    primaryLighter: '#8BA3FF', 
    
    // Status & Feedback Colors
    success: '#2ECC71', 
    warning: '#F39C12', 
    danger: '#E74C3C', 
    info: '#3498DB', 

    // Neutral Palette
    background: '#F0F2F5', // Light Gray Background (Main background)
    surface: '#FFFFFF', // Pure White (Card, Header, Input Background)
    darkText: '#2C3E50', // Dark charcoal (Used for all black text/icons)
    mediumText: '#556677', // Muted gray
    faintText: '#A0A7AD', // Very light gray (Placeholders)

    // Base Colors
    inputBase: '#E3E8EE', 
    headerBackground: '#fcfcfcff', 
    shadow: 'rgba(0, 0, 0, 0.15)',
    inputBorder: '#D8DCE3', 

    // --- GLASSMOPRHISM COLORS (Retained for old definitions) ---
    glassBgTop: '#4c00ff', 
    glassBgBottom: '#00ffc8', 
    glassSurface: 'rgba(255, 255, 255, 0.2)', 
    glassBorder: 'rgba(255, 255, 255, 0.8)', 
    forgotPasswordText: 'rgba(255, 255, 255, 0.9)',
    termsText: 'rgba(255, 255, 255, 0.7)',
};

export const styles = StyleSheet.create({
    // --- General Layouts ---
    safeArea: { flex: 1, backgroundColor: ColorConstants.background },
    detailWrapper: { flex: 1, backgroundColor: ColorConstants.background },
    profileSafeArea: { flex: 1, backgroundColor: ColorConstants.background },

    // --- LOGIN SCREEN (PROFESSIONAL UI) ---
    loginScreenContainer: { 
        flex: 1, 
        alignItems: 'center', 
        justifyContent: 'center',
        backgroundColor: ColorConstants.background,
    },
    keyboardAvoidingContainer: {
        flex: 1, 
        justifyContent: 'center', 
        alignItems: 'center',
        width: '100%',
    },
    loginCardStyle: { 
        backgroundColor: ColorConstants.surface,
        borderRadius: 20, 
        padding: 40,
        width: '90%', 
        maxWidth: 400, 
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 8 }, 
        shadowOpacity: 0.18,
        shadowRadius: 15,
        elevation: 12,
        alignItems: 'center',
    },
    loginLogoContainer: { 
        width: 90,
        height: 90,
        borderRadius: 45,
        backgroundColor: ColorConstants.surface,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 40,
        borderWidth: 3,
        borderColor: ColorConstants.primaryAccent,
        overflow: 'hidden',
    },
    loginLogoImage: { 
        width: '80%',
        height: '80%',
        resizeMode: 'contain',
    },
    loginWelcomeText: { 
        fontSize: 30,
        fontWeight: '800', 
        color: ColorConstants.darkText,
        marginBottom: 8,
        textAlign: 'center',
    },
    loginSignInText: { 
        fontSize: 17,
        color: ColorConstants.mediumText,
        marginBottom: 40,
        textAlign: 'center',
    },
    loginInputGroup: { 
        width: '100%',
        marginBottom: 25,
        position: 'relative',
        paddingVertical:12,
    },
    loginFloatingLabel: { 
        position: 'absolute',
        paddingHorizontal: 5,
        backgroundColor: ColorConstants.surface, 
        borderRadius: 5,
        fontWeight: '600',
    },
    loginInputWrapper: { 
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: ColorConstants.surface,
        borderWidth: 1.5,
        borderRadius: 10,
        height: 58,
        overflow: 'hidden',
    },
    loginTextInput: { 
        flex: 1,
        height: '100%',
        fontSize: 16,
        paddingHorizontal: 10,
        paddingVertical: 10,
        fontWeight: '500',
        color: ColorConstants.darkText, 
    },
    loginPasswordToggle: {
        paddingHorizontal: 15,
        height: '100%',
        justifyContent: 'center',
        alignItems: 'center',
    },
    loginForgotPasswordButton: {
        marginTop: 5,
        marginBottom: 40,
        alignSelf: 'flex-end',
        paddingHorizontal: 5,
    },
    loginForgotPasswordText: {
        fontSize: 15,
        fontWeight: '600',
        color: ColorConstants.mediumText,
    },
    loginButton: {
        backgroundColor: ColorConstants.primaryAccent,
        borderRadius: 10,
        height: 58,
        width: '100%',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 40,
        shadowColor: ColorConstants.primaryAccent,
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.35,
        shadowRadius: 8,
        elevation: 8,
    },
    loginButtonText: {
        color: ColorConstants.surface,
        fontSize: 18,
        fontWeight: '800',
        letterSpacing: 0.8,
    },
    loginTermsText: {
        fontSize: 13,
        color: ColorConstants.faintText,
        textAlign: 'center',
        lineHeight: 18,
    },
    // --- UTILITIES & DISABLED STYLES ---
    // disabledButton: { opacity: 0.6 },
    // disabledInput: { backgroundColor: '#ECF0F1', borderColor: ColorConstants.inputBorder },
    
    // --- TASK LIST & DETAIL STYLES ---
    header: { // PROFESSIONAL HEADER STYLE
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingVertical: 15,
        backgroundColor: ColorConstants.surface, // Light background
        borderBottomWidth: 1,
        borderBottomColor: ColorConstants.inputBorder,
        shadowColor: ColorConstants.shadow,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 5,
        elevation: 5,
    },
    title: { // "TASKS" Title
        fontSize: 24,
        fontWeight: '800',
        color: ColorConstants.darkText, // BLACK TITLE TEXT
        letterSpacing: 0.5,
    },
    profileIconContainer: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: ColorConstants.inputBase,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 2,
        borderColor: ColorConstants.darkText, // BLACK ICON BORDER
        overflow: 'hidden',
    },
    profileIconImage: {
        width: '100%',
        height: '100%',
    },
    profileIconText: {
        color: ColorConstants.darkText, // BLACK PROFILE TEXT
        fontWeight: 'bold',
        fontSize: 22,
    },
    // --- NAV BAR STYLES (PROFESSIONAL FIX) ---
    navbar: { 
        flexDirection: 'row',
        paddingHorizontal: 15,
        paddingVertical: 10,
    },
    taskCategoryContainer: {
        marginRight: 10, 
    },
    navItem: {
        paddingVertical: 12,
        paddingHorizontal: 18,
        borderRadius: 25, 
        backgroundColor: ColorConstants.surface, 
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: ColorConstants.inputBorder, 
    },
    activeNavItem: {
        backgroundColor: ColorConstants.primaryAccent,
        borderColor: ColorConstants.primaryAccent,
        shadowColor: ColorConstants.primaryAccent,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 4,
    },
    navItemText: {
        fontSize: 14,
        fontWeight: '600',
        color: ColorConstants.mediumText,
    },
    activeNavItemText: {
        color: ColorConstants.surface, 
        fontWeight: '700',
    },
    // --- SEARCH BAR STYLES ---
    searchContainer: { 
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: ColorConstants.surface,
        borderRadius: 15,
        marginVertical: 15, // Increased vertical margin for separation
        marginHorizontal: 15,
        paddingHorizontal: 15,
        shadowColor: ColorConstants.shadow,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 3,
        elevation: 3,
        borderWidth: 1,
        borderColor: ColorConstants.inputBorder,
    },
    searchIcon: { 
        marginRight: 10,
        color: ColorConstants.darkText, // BLACK ICON
    },
    searchInput: {
        flex: 1,
        height: 48,
        fontSize: 16,
        color: ColorConstants.darkText, // BLACK INPUT TEXT
    },
    content: {
        paddingHorizontal: 15,
        backgroundColor: ColorConstants.background,
    },
    card: {
        backgroundColor: ColorConstants.surface,
        borderRadius: 15,
        marginVertical: 8,
        padding: 20,
        borderLeftWidth: 5,
        shadowColor: ColorConstants.shadow,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    cardHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 10,
    },
    orderId: {
        fontSize: 18,
        fontWeight: 'bold',
        color: ColorConstants.darkText,
    },
    statusTag: {
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 15,
        alignItems: 'center',
    },
    statusText: {
        color: ColorConstants.surface,
        fontWeight: 'bold',
        fontSize: 12,
    },
    cardBody: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        flexWrap: 'wrap',
    },
    cardDetails: {
        width: '48%',
    },
    detailText: {
        fontSize: 14,
        color: ColorConstants.darkText,
        marginBottom: 5,
    },
    label: {
        fontWeight: 'bold',
        color: ColorConstants.darkText,
    },
    blueText: {
        color: ColorConstants.info, 
        fontWeight: 'bold',
    },
    noTasksText: {
        textAlign: 'center',
        marginTop: 20,
        fontSize: 16,
        color: ColorConstants.faintText,
    },
    detailHeaderBar: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 15,
        paddingVertical: 15,
        backgroundColor: ColorConstants.surface,
        borderBottomLeftRadius: 20,
        borderBottomRightRadius: 20,
        shadowColor: ColorConstants.shadow,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 3,
        elevation: 4,
    },
    backButton: { padding: 5 },
    detailScreenTitle: {
        fontSize: 22,
        fontWeight: '700',
        color: ColorConstants.darkText,
    },
    detailPlaceholder: { width: 24 },
    detailScrollView: { padding: 15 },
    detailSection: {
        backgroundColor: ColorConstants.surface,
        borderRadius: 15,
        padding: 20,
        marginBottom: 15,
        shadowColor: ColorConstants.shadow,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    detailItemText: {
        fontSize: 15,
        color: ColorConstants.darkText,
        marginBottom: 8,
        lineHeight: 22,
    },
    detailLabel: {
        fontWeight: 'bold',
        color: ColorConstants.darkText,
    },
    detailActiveStatus: {
        color: ColorConstants.success,
        fontWeight: 'bold',
    },
    detailStatusText: {
        fontWeight: 'bold',
        color: ColorConstants.surface,
        paddingHorizontal: 8,
        paddingVertical: 2,
        borderRadius: 10,
        overflow: 'hidden',
    },
    uploadSection: {
        backgroundColor: ColorConstants.surface,
        borderRadius: 15,
        padding: 20,
        marginBottom: 15,
        shadowColor: ColorConstants.shadow,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    uploadTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: ColorConstants.darkText,
        marginBottom: 15,
    },
    uploadBox: {
        borderWidth: 2,
        borderColor: '#E6E6FA',
        borderStyle: 'dashed',
        borderRadius: 15,
        padding: 25,
        alignItems: 'center',
        marginBottom: 15,
        backgroundColor: '#F7F9FF',
    },
    uploadText: {
        fontSize: 16,
        fontWeight: '600',
        color: ColorConstants.faintText,
        marginTop: 10,
    },
    uploadSubText: {
        fontSize: 12,
        color: ColorConstants.faintText,
        marginTop: 5,
    },
    gallery: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        marginTop: 10,
    },
    thumbnailImage: {
        width: 80,
        height: 80,
        borderRadius: 10,
        marginRight: 10,
        marginBottom: 10,
        borderWidth: 1,
        borderColor: '#E6E6FA',
    },
    thumbnailAdd: {
        width: 80,
        height: 80,
        borderRadius: 10,
        backgroundColor: '#F7F9FF',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 2,
        borderColor: '#E6E6FA',
        borderStyle: 'dashed',
    },
    commentsSection: {
        backgroundColor: ColorConstants.surface,
        borderRadius: 15,
        padding: 20,
        marginBottom: 15,
        shadowColor: ColorConstants.shadow,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    commentsTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: ColorConstants.darkText,
        marginBottom: 10,
    },
    commentsInput: {
        borderWidth: 1,
        borderColor: ColorConstants.inputBorder,
        borderRadius: 10,
        padding: 15,
        minHeight: 100,
        textAlignVertical: 'top',
        fontSize: 16,
        backgroundColor: ColorConstants.inputBase,
        color: ColorConstants.darkText,
    },
    locationSection: {
        backgroundColor: ColorConstants.surface,
        borderRadius: 15,
        padding: 20,
        marginBottom: 15,
        shadowColor: ColorConstants.shadow,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    locationHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 10,
    },
    locationTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: ColorConstants.darkText,
        marginLeft: 10,
    },
    locationText: {
        fontSize: 14,
        color: ColorConstants.darkText,
        marginLeft: 30,
        marginBottom: 5,
    },
    lastUpdatedText: {
        fontSize: 12,
        color: ColorConstants.faintText,
        marginLeft: 30,
        marginTop: 5,
    },
    actionButtons: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        padding: 15,
    },
    rejectButton: {
        flex: 1,
        backgroundColor: ColorConstants.danger,
        padding: 15,
        borderRadius: 15,
        marginRight: 10,
        alignItems: 'center',
        shadowColor: ColorConstants.danger,
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.4,
        shadowRadius: 8,
        elevation: 8,
    },
    rejectButtonText: {
        color: ColorConstants.surface,
        fontWeight: 'bold',
        fontSize: 16,
    },
    submitButton: {
        flex: 1,
        backgroundColor: ColorConstants.primaryAccent,
        padding: 15,
        borderRadius: 15,
        marginLeft: 10,
        alignItems: 'center',
        shadowColor: ColorConstants.primaryAccent,
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.4,
        shadowRadius: 8,
        elevation: 8,
    },
    submitButtonText: {
        color: ColorConstants.surface,
        fontWeight: 'bold',
        fontSize: 16,
    },
    // --- DISABLED BUTTON STYLES (Single Definition) ---
    disabledButton: {
        backgroundColor: ColorConstants.faintText,
        shadowColor: 'transparent',
        elevation: 0,
    },
    disabledButtonText: {
        color: '#E0E0E0', 
    },
    disabledInput: {
        backgroundColor: '#ECF0F1',
        color: ColorConstants.faintText,
    },
    // --- PROFILE STYLES ---
    profileHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingVertical: 15,
        borderBottomWidth: 1,
        borderBottomColor: '#ECF0F1',
        backgroundColor: ColorConstants.surface,
        borderBottomLeftRadius: 20,
        borderBottomRightRadius: 20,
        shadowColor: ColorConstants.shadow,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 5,
        elevation: 8,
    },
    profileTitle: {
        fontSize: 24,
        fontWeight: '700',
        color: ColorConstants.darkText,
        letterSpacing: 1,
    },
    profileContent: {
        alignItems: 'center',
        paddingTop: 30,
        backgroundColor: ColorConstants.background,
        flex: 1,
        width: '100%',
        maxWidth: 600,
        alignSelf: 'center',
    },
    profileScrollView: {
        flexGrow: 1,
        backgroundColor: ColorConstants.background,
        paddingHorizontal: 20,
        alignItems: 'center',
    },
    profileAvatarContainer: {
        width: 120,
        height: 120,
        borderRadius: 60,
        backgroundColor: ColorConstants.surface,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 15,
        position: 'relative',
        borderWidth: 3,
        borderColor: ColorConstants.primaryAccent,
        shadowColor: ColorConstants.shadow,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 8,
    },
    profileAvatar: { opacity: 0.8 },
    profileAvatarImage: {
        width: '100%',
        height: '100%',
        borderRadius: 60,
    },
    cameraIconContainer: {
        position: 'absolute',
        bottom: 0,
        right: 0,
        backgroundColor: ColorConstants.primaryAccent,
        padding: 8,
        borderRadius: 20,
        borderWidth: 2,
        borderColor: ColorConstants.background,
    },
    nameDisplayContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 5,
    },
    nameEditContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 5,
        backgroundColor: ColorConstants.surface,
        borderRadius: 10,
        paddingHorizontal: 10,
        paddingVertical: 5,
        borderWidth: 1,
        borderColor: '#E6E6FA',
    },
    profileName: {
        fontSize: 24,
        fontWeight: '700',
        color: ColorConstants.darkText,
        marginRight: 10,
    },
    profileNameInput: {
        fontSize: 24,
        fontWeight: '700',
        color: ColorConstants.darkText,
        minWidth: 100,
    },
    nameEditIcon: {
        padding: 5,
    },
    profileEmail: {
        fontSize: 16,
        color: ColorConstants.mediumText,
        marginBottom: 30,
    },
    profileMenu: {
        width: '100%',
        marginBottom: 20,
        paddingHorizontal: 10,
    },
    profileMenuItem: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: ColorConstants.surface,
        paddingVertical: 15,
        paddingHorizontal: 15,
        borderRadius: 12,
        marginBottom: 10,
        shadowColor: ColorConstants.shadow,
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 3,
        elevation: 2,
    },
    profileMenuItemText: {
        flex: 1,
        marginLeft: 15,
        fontSize: 16,
        color: ColorConstants.darkText,
        fontWeight: '500',
    },
    logoutButton: {
        width: '95%',
        backgroundColor: ColorConstants.danger,
        padding: 15,
        borderRadius: 12,
        alignItems: 'center',
        marginTop: 20,
        marginBottom: 30,
        shadowColor: ColorConstants.danger,
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.4,
        shadowRadius: 8,
        elevation: 8,
    },
    logoutButtonText: {
        color: ColorConstants.surface,
        fontSize: 18,
        fontWeight: 'bold',
    },
    versionText: {
        fontSize: 14,
        color: ColorConstants.faintText,
        marginBottom: 20,
    },
    noNotificationsText: {
        fontSize: 18,
        color: ColorConstants.faintText,
        marginTop: 20,
        textAlign: 'center',
    },
});


// AppStyles.ts
// import { StyleSheet, ViewStyle, TextStyle } from 'react-native';

// // Define explicit types for your color constants
// export interface ColorConstant {
//     color: string;
// }

// export interface BackgroundColorConstant {
//     backgroundColor: string;
// }

// export const ColorConstants = {
//     lightBackground: '#F8F9FA',
//     darkBackground: '#FFFFFF',
//     primaryColor: '#4A69E1',
//     accentColor: '#2ECC71',
//     darkText: '#2C3E50',
//     faintText: '#A0A7AD',
//     overdueColor: '#E74C3C',
//     submittedColor: '#2ECC71',
//     completedColor: '#4A69E1',
//     rejectedColor: '#E74C3C',
//     pendingColor: '#F39C12',
// };

// // We define styles.xxxColor as objects only if they are used as background containers in TaskCard, 
// // but we will simplify the usage by exporting the raw color hex codes.

// export const styles = StyleSheet.create({
//     // --- Colors that must be accessed as {color: string} or {backgroundColor: string} ---
//     lightBackground: { color: ColorConstants.lightBackground },
//     darkBackground: { color: ColorConstants.darkBackground },
//     primaryColor: { color: ColorConstants.primaryColor },
//     accentColor: { color: ColorConstants.accentColor },
//     darkText: { color: ColorConstants.darkText },
//     faintText: { color: ColorConstants.faintText },
    
//     // Status colors must be treated as background styles for containers
//     overdueColor: { backgroundColor: ColorConstants.overdueColor },
//     submittedColor: { backgroundColor: ColorConstants.submittedColor },
//     completedColor: { backgroundColor: ColorConstants.completedColor },
//     rejectedColor: { backgroundColor: ColorConstants.rejectedColor },
//     pendingColor: { backgroundColor: ColorConstants.pendingColor },

//     // --- General Layouts ---
//     safeArea: {
//         backgroundColor: ColorConstants.lightBackground,
//     },
//     loginContainer: {
//         flex: 1,
//         justifyContent: 'center',
//         alignItems: 'center',
//         padding: 20,
//         backgroundColor: ColorConstants.lightBackground,
//     },
//     detailWrapper: {
//         flex: 1,
//         backgroundColor: ColorConstants.lightBackground,
//     },
//     profileSafeArea: {
//         flex: 1,
//         backgroundColor: ColorConstants.lightBackground,
//     },

//     // --- Login Screen ---
//     loginImage: {
//         width: 200,
//         height: 200,
//         marginBottom: 40,
//         borderRadius: 100,
//         resizeMode: 'contain',
//     },
//     loginTitle: {
//         fontSize: 32,
//         fontWeight: '700',
//         color: ColorConstants.darkText,
//         marginBottom: 30,
//         letterSpacing: 1.5,
//     },
//     input: {
//         width: '100%',
//         maxWidth: 320,
//         height: 55,
//         backgroundColor: 'rgba(255, 255, 255, 0.8)',
//         borderRadius: 15,
//         paddingHorizontal: 20,
//         marginBottom: 15,
//         fontSize: 16,
//         borderWidth: 1,
//         borderColor: 'rgba(255, 255, 255, 0.3)',
//         shadowColor: '#000',
//         shadowOffset: { width: 0, height: 2 },
//         shadowOpacity: 0.1,
//         shadowRadius: 5,
//         elevation: 3,
//         // Ensure text color is set for TextInput, which will override the ViewStyle part
//         color: ColorConstants.darkText, 
//     } as ViewStyle & TextStyle, // Type casting for compound styles like TextInput
//     inputFocused: {
//         borderColor: ColorConstants.primaryColor,
//         borderWidth: 2,
//     },
//     loginButton: {
//         width: '100%',
//         maxWidth: 320,
//         height: 55,
//         backgroundColor: ColorConstants.primaryColor,
//         borderRadius: 15,
//         justifyContent: 'center',
//         alignItems: 'center',
//         marginTop: 10,
//         shadowColor: ColorConstants.primaryColor,
//         shadowOffset: { width: 0, height: 6 },
//         shadowOpacity: 0.4,
//         shadowRadius: 8,
//         elevation: 8,
//     },
//     loginButtonText: {
//         color: ColorConstants.darkBackground,
//         fontSize: 18,
//         fontWeight: 'bold',
//         letterSpacing: 0.5,
//     },

//     // --- Task List Header & Navigation ---
//     header: {
//         flexDirection: 'row',
//         justifyContent: 'space-between',
//         alignItems: 'center',
//         paddingHorizontal: 20,
//         paddingVertical: 15,
//         backgroundColor: '#153050ff',
//         borderBottomLeftRadius: 20,
//         borderBottomRightRadius: 20,
//         shadowColor: '#000',
//         shadowOffset: { width: 0, height: 4 },
//         shadowOpacity: 0.2,
//         shadowRadius: 6,
//         elevation: 8,
//     },
//     title: {
//         fontSize: 24,
//         fontWeight: '700',
//         color: ColorConstants.darkBackground,
//         letterSpacing: 1,
//     },
//     profileIconContainer: {
//         width: 40,
//         height: 40,
//         borderRadius: 20,
//         backgroundColor: ColorConstants.darkBackground,
//         justifyContent: 'center',
//         alignItems: 'center',
//         borderWidth: 2,
//         borderColor: ColorConstants.darkBackground,
//         overflow: 'hidden',
//     },
//     profileIconImage: {
//         width: '100%',
//         height: '100%',
//     },
//     profileIconText: {
//         color: '#1C2A3A',
//         fontWeight: 'bold',
//         fontSize: 22,
//     },
// // --- Task List Header & Navigation ---
// // --- Navigation Bar Styles ---
// navbar: {
//   flexDirection: 'row',
//   paddingHorizontal: 4,
//   paddingVertical: 6,
//   // Removed alignItems: 'justify-between', as it's not a valid RN style property
// },

// taskCategoryContainer: {
//   marginRight: 10,
//   paddingLeft: 10
// },

// navItem: {
//   paddingVertical: 12,
//   paddingHorizontal: 18,
//   borderRadius: 20,
//   backgroundColor: '#E8F0F7',
//   justifyContent: 'center',
//   alignItems: 'center',
// },

// activeNavItem: {
//   backgroundColor: ColorConstants.primaryColor,
// },

// navItemText: {
//   fontSize: 14,
//   fontWeight: '600',
//   color: '#4975a7',
// },

// activeNavItemText: {
//   color: ColorConstants.darkBackground,
//   fontWeight: '700',
// },


//     // --- Task List Content ---
//     searchContainer: {
//         flexDirection: 'row',
//         alignItems: 'center',
//         backgroundColor: ColorConstants.darkBackground,
//         borderRadius: 15,
//         marginVertical: 10,
//         marginHorizontal: 10,
//         paddingHorizontal: 15,
//         shadowColor: '#000',
//         shadowOffset: { width: 0, height: 2 },
//         shadowOpacity: 0.1,
//         shadowRadius: 3,
//         elevation: 3,
//     },
//     searchIcon: {
//         marginRight: 10,
//     },
//     searchInput: {
//         flex: 1,
//         height: 48,
//         fontSize: 16,
//         color: ColorConstants.darkText,
//     },
//     content: {
//         flexGrow: 1,
//         paddingHorizontal: 10,
//         backgroundColor: ColorConstants.lightBackground,
//     },
//     card: {
//         backgroundColor: ColorConstants.darkBackground,
//         borderRadius: 15,
//         marginVertical: 8,
//         padding: 20,
//         borderLeftWidth: 5,
//         borderLeftColor: ColorConstants.primaryColor,
//     },
//     cardHeader: {
//         flexDirection: 'row',
//         justifyContent: 'space-between',
//         alignItems: 'center',
//         marginBottom: 10,
//     },
//     orderId: {
//         fontSize: 16,
//         fontWeight: 'bold',
//         color: ColorConstants.darkText,
//     },
//     statusTag: {
//         paddingHorizontal: 12,
//         paddingVertical: 5,
//         borderRadius: 20,
//     },
//     // We already defined these as background styles above. Keeping duplicates for safety
//     pendingStatus: { backgroundColor: ColorConstants.pendingColor },
//     overdueStatus: { backgroundColor: ColorConstants.overdueColor },
//     submittedStatus: { backgroundColor: ColorConstants.submittedColor },
//     completedStatus: { backgroundColor: ColorConstants.completedColor },
//     rejectedStatus: { backgroundColor: ColorConstants.rejectedColor },
//     statusText: {
//         color: ColorConstants.darkBackground,
//         fontWeight: 'bold',
//         fontSize: 12,
//     },
//     cardBody: {
//         flexDirection: 'row',
//         justifyContent: 'space-between',
//         flexWrap: 'wrap',
//     },
//     cardDetails: {
//         width: '48%',
//     },
//     detailText: {
//         fontSize: 14,
//         color: ColorConstants.darkText,
//         marginBottom: 5,
//     },
//     label: {
//         fontWeight: 'bold',
//         color: ColorConstants.darkText,
//     },
//     blueText: {
//         color: '#fcfdffff', // Note: This color is hardcoded and looks like a typo, keeping for consistency.
//         fontWeight: 'bold',
//     },
//     noTasksText: {
//         textAlign: 'center',
//         marginTop: 20,
//         fontSize: 16,
//         color: ColorConstants.faintText,
//     },

//     // --- Task Detail Screen ---
//     detailHeaderBar: {
//         flexDirection: 'row',
//         alignItems: 'center',
//         justifyContent: 'space-between',
//         paddingHorizontal: 15,
//         paddingVertical: 15,
//         backgroundColor: ColorConstants.darkBackground,
//         borderBottomLeftRadius: 20,
//         borderBottomRightRadius: 20,
//         shadowColor: '#000',
//         shadowOffset: { width: 0, height: 2 },
//         shadowOpacity: 0.1,
//         shadowRadius: 3,
//         elevation: 4,
//     },
//     backButton: { padding: 5 },
//     detailScreenTitle: {
//         fontSize: 22,
//         fontWeight: '700',
//         color: ColorConstants.darkText,
//     },
//     detailPlaceholder: { width: 24 },
//     detailScrollView: { padding: 15 },
//     detailSection: {
//         backgroundColor: ColorConstants.darkBackground,
//         borderRadius: 15,
//         padding: 20,
//         marginBottom: 15,
//         shadowColor: '#000',
//         shadowOffset: { width: 0, height: 2 },
//         shadowOpacity: 0.1,
//         shadowRadius: 4,
//         elevation: 3,
//     },
//     detailItemText: {
//         fontSize: 15,
//         color: ColorConstants.darkText,
//         marginBottom: 8,
//         lineHeight: 22,
//     },
//     detailLabel: {
//         fontWeight: 'bold',
//         color: ColorConstants.darkText,
//     },
//     detailActiveStatus: {
//         color: ColorConstants.accentColor,
//         fontWeight: 'bold',
//     },
//     detailStatusText: {
//         fontWeight: 'bold',
//         color: ColorConstants.darkBackground,
//         paddingHorizontal: 8,
//         paddingVertical: 2,
//         borderRadius: 10,
//         overflow: 'hidden',
//     },
//     uploadSection: {
//         backgroundColor: ColorConstants.darkBackground,
//         borderRadius: 15,
//         padding: 20,
//         marginBottom: 15,
//         shadowColor: '#000',
//         shadowOffset: { width: 0, height: 2 },
//         shadowOpacity: 0.1,
//         shadowRadius: 4,
//         elevation: 3,
//     },
//     uploadTitle: {
//         fontSize: 18,
//         fontWeight: '700',
//         color: ColorConstants.darkText,
//         marginBottom: 15,
//     },
//     uploadBox: {
//         borderWidth: 2,
//         borderColor: '#E6E6FA',
//         borderStyle: 'dashed',
//         borderRadius: 15,
//         padding: 25,
//         alignItems: 'center',
//         marginBottom: 15,
//         backgroundColor: '#F7F9FF',
//     },
//     uploadText: {
//         fontSize: 16,
//         fontWeight: '600',
//         color: ColorConstants.faintText,
//         marginTop: 10,
//     },
//     uploadSubText: {
//         fontSize: 12,
//         color: ColorConstants.faintText,
//         marginTop: 5,
//     },
//     gallery: {
//         flexDirection: 'row',
//         flexWrap: 'wrap',
//         marginTop: 10,
//     },
//     thumbnailImage: {
//         width: 80,
//         height: 80,
//         borderRadius: 10,
//         marginRight: 10,
//         marginBottom: 10,
//         borderWidth: 1,
//         borderColor: '#E6E6FA',
//     },
//     thumbnailAdd: {
//         width: 80,
//         height: 80,
//         borderRadius: 10,
//         backgroundColor: '#F7F9FF',
//         justifyContent: 'center',
//         alignItems: 'center',
//         borderWidth: 2,
//         borderColor: '#E6E6FA',
//         borderStyle: 'dashed',
//     },
//     commentsSection: {
//         backgroundColor: ColorConstants.darkBackground,
//         borderRadius: 15,
//         padding: 20,
//         marginBottom: 15,
//         shadowColor: '#000',
//         shadowOffset: { width: 0, height: 2 },
//         shadowOpacity: 0.1,
//         shadowRadius: 4,
//         elevation: 3,
//     },
//     commentsTitle: {
//         fontSize: 18,
//         fontWeight: '700',
//         color: ColorConstants.darkText,
//         marginBottom: 10,
//     },
//     commentsInput: {
//         borderWidth: 1,
//         borderColor: '#E6E6FA',
//         borderRadius: 10,
//         padding: 15,
//         minHeight: 100,
//         textAlignVertical: 'top',
//         fontSize: 16,
//         backgroundColor: '#F7F9FF',
//         color: ColorConstants.darkText,
//     },
//     locationSection: {
//         backgroundColor: ColorConstants.darkBackground,
//         borderRadius: 15,
//         padding: 20,
//         marginBottom: 15,
//         shadowColor: '#000',
//         shadowOffset: { width: 0, height: 2 },
//         shadowOpacity: 0.1,
//         shadowRadius: 4,
//         elevation: 3,
//     },
//     locationHeader: {
//         flexDirection: 'row',
//         alignItems: 'center',
//         marginBottom: 10,
//     },
//     locationTitle: {
//         fontSize: 18,
//         fontWeight: '700',
//         color: ColorConstants.darkText,
//         marginLeft: 10,
//     },
//     locationText: {
//         fontSize: 14,
//         color: ColorConstants.darkText,
//         marginLeft: 30,
//         marginBottom: 5,
//     },
//     lastUpdatedText: {
//         fontSize: 12,
//         color: ColorConstants.faintText,
//         marginLeft: 30,
//         marginTop: 5,
//     },
//     actionButtons: {
//         flexDirection: 'row',
//         justifyContent: 'space-between',
//         padding: 15,
//     },
//     rejectButton: {
//         flex: 1,
//         backgroundColor: ColorConstants.rejectedColor,
//         padding: 15,
//         borderRadius: 15,
//         marginRight: 10,
//         alignItems: 'center',
//         shadowColor: ColorConstants.rejectedColor,
//         shadowOffset: { width: 0, height: 6 },
//         shadowOpacity: 0.4,
//         shadowRadius: 8,
//         elevation: 8,
//     },
//     rejectButtonText: {
//         color: ColorConstants.darkBackground,
//         fontWeight: 'bold',
//         fontSize: 16,
//     },
//     submitButton: {
//         flex: 1,
//         backgroundColor: ColorConstants.primaryColor,
//         padding: 15,
//         borderRadius: 15,
//         marginLeft: 10,
//         alignItems: 'center',
//         shadowColor: ColorConstants.primaryColor,
//         shadowOffset: { width: 0, height: 6 },
//         shadowOpacity: 0.4,
//         shadowRadius: 8,
//         elevation: 8,
//     },
//     submitButtonText: {
//         color: ColorConstants.darkBackground,
//         fontWeight: 'bold',
//         fontSize: 16,
//     },
//     disabledButton: {
//         backgroundColor: '#BDC3C7',
//         shadowColor: 'transparent',
//         elevation: 0,
//     },
//     disabledButtonText: {
//         color: '#E0E0E0',
//     },
//     disabledInput: {
//         backgroundColor: '#ECF0F1',
//         color: '#BDC3C7',
//     },
//     // --- Profile Screen ---
//     profileHeader: {
//         flexDirection: 'row',
//         justifyContent: 'space-between',
//         alignItems: 'center',
//         paddingHorizontal: 20,
//         paddingVertical: 15,
//         borderBottomWidth: 1,
//         borderBottomColor: '#ECF0F1',
//         backgroundColor: ColorConstants.darkBackground,
//         borderBottomLeftRadius: 20,
//         borderBottomRightRadius: 20,
//         shadowColor: '#000',
//         shadowOffset: { width: 0, height: 4 },
//         shadowOpacity: 0.1,
//         shadowRadius: 5,
//         elevation: 8,
//     },
//     profileTitle: {
//         fontSize: 24,
//         fontWeight: '700',
//         color: ColorConstants.darkText,
//         letterSpacing: 1,
//     },
//     profileContent: {
//         alignItems: 'center',
//         paddingVertical: 30,
//         backgroundColor: ColorConstants.lightBackground,
//         flex: 1,
//     },
//     profileAvatarContainer: {
//         width: 120,
//         height: 120,
//         borderRadius: 60,
//         backgroundColor: '#ECF0F1',
//         justifyContent: 'center',
//         alignItems: 'center',
//         marginBottom: 20,
//         position: 'relative',
//         shadowColor: '#000',
//         shadowOffset: { width: 0, height: 4 },
//         shadowOpacity: 0.1,
//         shadowRadius: 8,
//         elevation: 8,
//     },
//     profileAvatar: { opacity: 0.8 },
//     profileAvatarImage: {
//         width: '100%',
//         height: '100%',
//         borderRadius: 60,
//     },
//     cameraIconContainer: {
//         position: 'absolute',
//         bottom: 0,
//         right: 0,
//         backgroundColor: ColorConstants.primaryColor,
//         padding: 8,
//         borderRadius: 20,
//         borderWidth: 2,
//         borderColor: ColorConstants.lightBackground,
//     },
//     nameDisplayContainer: {
//         flexDirection: 'row',
//         alignItems: 'center',
//         marginBottom: 5,
//     },
//     nameEditContainer: {
//         flexDirection: 'row',
//         alignItems: 'center',
//         marginBottom: 5,
//         backgroundColor: 'rgba(255, 255, 255, 0.8)',
//         borderRadius: 10,
//         paddingHorizontal: 10,
//         paddingVertical: 5,
//         borderWidth: 1,
//         borderColor: 'rgba(255, 255, 255, 0.3)',
//     },
//     profileName: {
//         fontSize: 22,
//         fontWeight: 'bold',
//         color: ColorConstants.darkText,
//         marginRight: 10,
//     },
//     profileNameInput: {
//         fontSize: 22,
//         fontWeight: 'bold',
//         color: ColorConstants.darkText,
//         minWidth: 100,
//     },
//     nameEditIcon: {
//         padding: 5,
//     },
//     profileEmail: {
//         fontSize: 16,
//         color: ColorConstants.faintText,
//         marginBottom: 30,
//     },
//     profileMenu: {
//         width: '90%',
//         backgroundColor: ColorConstants.darkBackground,
//         borderRadius: 15,
//         shadowColor: '#000',
//         shadowOffset: { width: 0, height: 2 },
//         shadowOpacity: 0.1,
//         shadowRadius: 4,
//         elevation: 3,
//         marginBottom: 30,
//     },
//     profileMenuItem: {
//         flexDirection: 'row',
//         alignItems: 'center',
//         paddingVertical: 18,
//         paddingHorizontal: 20,
//         borderBottomWidth: 1,
//         borderBottomColor: '#ECF0F1',
//     },
//     profileMenuItemText: {
//         flex: 1,
//         fontSize: 16,
//         color: ColorConstants.darkText,
//         marginLeft: 15,
//     },
//     logoutButton: {
//         width: '90%',
//         paddingVertical: 18,
//         backgroundColor: ColorConstants.rejectedColor,
//         borderRadius: 15,
//         justifyContent: 'center',
//         alignItems: 'center',
//         marginBottom: 20,
//         shadowColor: ColorConstants.rejectedColor,
//         shadowOffset: { width: 0, height: 6 },
//         shadowOpacity: 0.4,
//         shadowRadius: 8,
//         elevation: 8,
//     },
//     logoutButtonText: {
//         color: ColorConstants.darkBackground,
//         fontSize: 18,
//         fontWeight: 'bold',
//     },
//     versionText: {
//         fontSize: 14,
//         color: ColorConstants.faintText,
//         marginTop: 10,
//     },
//     noNotificationsText: {
//         fontSize: 18,
//         color: ColorConstants.faintText,
//         marginTop: 20,
//         textAlign: 'center',
//     },
// });
